    </title>

    <link rel="stylesheet" href="css/style.css" type="text/css" />
    <!-- <link rel="shortcut icon" href="images/seattle_skyline.jpg" /> -->
   	<style type="text/css">
	.style1 {
		color: #651413;
	}
	</style>
	
</head>

<body>


<div class="header">
<div class="left">
<p><br/>
<a href="./">Cloud Computing and Storage </a><br/>
Microsoft Research<br/>
Email: jinl@microsoft.com </p>
</div>
<div class="right">
</div>
</div>

<div id="container">
<div id="navcontainer">
<!--#include file ="menu.inc" -->

</div>
<div id="contents">

