<div class="navlist">
<ul>
<li><a href="default.aspx">Home</a></li>
<li><a href="default.aspx">People</a></li>
<ul class="subnavlist">
<li><a href="https://www.linkedin.com/in/bruno-bozza-7b25093">Bruno Bozza</a></li>
<li><a href="https://www.linkedin.com/in/yuxiao-hu-8530208">Yuxiao Hu</a></li>
<li><a href="http://research.microsoft.com/~chengh">Cheng Huang</a></li>
<li><a href="http://research.microsoft.com/~jinl">Jin Li</a></li>
<li><a href="http://research.microsoft.com/en-us/people/sanjeevm">Sanjeev Mehrotra</a></li>
<li><a href="http://research.microsoft.com/~sudipta">Sudipta Sengupta</a></li>
<li><a href="http://research.microsoft.com/en-us/people/leizhang/">Lei Zhang</a></li>
<li><a href="https://www.linkedin.com/in/weirong">Weirong Zhu</a></li>
</ul>

<div class="center"></div>

<div class="center"></div>
</div>

