<div class="navlist">
<ul>
<li><a href="default.aspx">Home</a></li>
<li><a href="default.aspx">People</a></li>
<ul class="subnavlist">
<li><a href="http://research.microsoft.com/en-us/people/xshua">Xian-Sheng Hua</a></li>
<li><a href="http://research.microsoft.com/~chengh">Cheng Huang</a></li>
<li><a href="http://research.microsoft.com/~jinl">Jin Li</a></li>
<li><a href="http://research.microsoft.com/en-us/people/sanjeevm">Sanjeev Mehrotra</a></li>
<li><a href="http://research.microsoft.com/~sudipta">Sudipta Sengupta</a></li>
</ul>

<div class="center"></div>

<div class="center"></div>
</div>

