<div class="navlist">
<ul>

<li><a href="default.aspx">Home</a></li>

<li><a href="default.aspx">Researches</a>
<ul class="subnavlist">
<!--<li><a href="research/methodology.aspx">Methodology</a></li>-->
<li><a href="research/computing.aspx">Cloud Compute</a></li>
<li><a href="research/storage.aspx">Storage</a></li>
<li><a href="research/networking.aspx">Communication & Networking</a></li>
<li><a href="research/compression.aspx">Compression</a></li>


</ul>
<!--
</li> 
<li>  <a href="publication/publication.aspx">Publications</a>
<ul class="subnavlist">
<li><a href="publication/publication.aspx">Selected Works</a>
<li><a href="publication/cited.aspx">Highly Cited Publications</a> -
<li><a href="publication/patents.aspx">Issued Patents</a>
<li><a href="publication/pending.aspx">Pending Patents</a>
</ul>
</li>
-->


<li><a href="CV/Bio_jinl.txt">Bio</a></li>
<li><a href="CV/Resume_jinl_2016.pdf">Resume [PDF]</a></li>
<li><a href="CV/CV_jinl_2016.pdf">CV [PDF]</a></li>

<!--
<li><a href="../about.aspx">More about Jin Li</a>
<ul class="subnavlist">
<li><a href="../highlight.aspx">Career Highlight</a></li>
<li><a href="../CV/CV_jinl.pdf">CV [PDF]</a></li>
</ul>
</li> 
-->

<li><a href="fun.aspx">Fun Fact</a>



<div class="center"></div>
<div class="center"></div>
</div>

