<a href="../1999/rd_optimization.aspx">publication/rd_optimization.aspx</a><%@ Page Language="C#" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN"
"http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd"><html xmlns="http://www.w3.org/1999/xhtml"><head><title>Jin Li's home page
    </title><link rel="stylesheet" href="../css/style.css" type="text/css" /><!-- <link rel="shortcut icon" href="../images/seattle_skyline.jpg" /> --><style type="text/css">
	.style1 {
		color: #651413;
	}
	</style></head><body><div class="header">
<div class="left">
<p><br/>
<a href="./">Jin Li, Principal Researcher & Manager </a><br/>
Multimedia Communication and Storage<br/>
Microsoft Research<br/>
Email: jinl@microsoft.com </p>
</div>
<div class="right">
</div>
</div>

<div id="container">
<div id="navcontainer">
<!--#include file ="menu.inc" -->

</div>
<div id="contents">

