<div class="navlist">
<ul>

<li><a href="../default.aspx">Home</a></li>

<li><a href="../research/research.aspx">Researches</a>
<ul class="subnavlist">
<li><a href="../research/methodology.aspx">Methodology</a></li>
<li><a href="../research/compression.aspx">Compression</a></li>
<li><a href="../research/networking.aspx">Communication & Networking</a></li>
<li><a href="../research/storage.aspx">Storage</a></li>
</ul>
</li>

<li>  <a href="../publication/publication.aspx">Publications</a>
<ul class="subnavlist">
<li><a href="../publication/publication.aspx">Selected Works</a>
<!-- <li><a href="../publication/cited.aspx">Highly Cited Publications</a> -->
<li><a href="../publication/patents.aspx">Issued Patents</a>
<li><a href="../publication/pending.aspx">Pending Patents</a>
</ul>
</li>


<li><a href="../about.aspx">More about Jin Li</a>
<ul class="subnavlist">
<li><a href="../highlight.aspx">Career Highlight</a></li>
<li><a href="../CV/CV_jinl.pdf">CV [PDF]</a></li>
<li><a href="../CV/Bio_jinl.txt">Bio [TXT]</a></li>
</ul>
</li> 

<li><a href="../../oldhome.html">Old Webpage</a>



<div class="center"></div>
<div class="center"></div>
</div>

