</div>

<div id="footer">
<SCRIPT LANGUAGE="JavaScript">
<!-- Begin
Stamp = new Date();
year = Stamp.getYear();
if (year < 2000) year = 1900 + year;
document.write('<font size="2" face="Arial"><B>' + (Stamp.getMonth() + 1) +"/"+Stamp.getDate()+ "/"+ year + '</B></font><BR>');
var Hours;
var Mins;
var Time;
Hours = Stamp.getHours();
if (Hours >= 12) {
Time = " P.M.";
}
else {
Time = " A.M.";
}
if (Hours > 12) {
Hours -= 12;
}
if (Hours == 0) {
Hours = 12;
}
Mins = Stamp.getMinutes();
if (Mins < 10) {
Mins = "0" + Mins;
} 
document.write('<B>' + Hours + ":" + Mins + Time + '</B>');
// End -->
</SCRIPT>
Number of Unique Visitors: 
<a href="http://www.easycounter.com/">
<img src="http://www.easycounter.com/counter.php?jinl,sapphire03"
border="0" alt="stats counter"></a>
<br><a href="http://www.easycounter.com/">HTML Counter</a>

</body>


</html>
