vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|02 Apr 2009 18:36:03 -0000
vti_extenderversion:SR|12.0.0.4518
vti_author:SR|REDMOND\\jinl
vti_modifiedby:SR|REDMOND\\jinl
vti_timecreated:TR|19 Feb 2008 07:25:21 -0000
vti_backlinkinfo:VX|
vti_syncwith_localhost\\\\\\research\\root\\web\\external\\http\\workshops\\pv2009///research/root/web/external/http/workshops/pv2009:TX|17 Jul 2008 00:02:50 -0000
vti_syncofs_localhost\\\\\\research\\root\\web\\external\\http\\workshops\\pv2009///research/root/web/external/http/workshops/pv2009:TW|17 Jul 2008 01:59:22 -0000
vti_nexttolasttimemodified:TW|02 Apr 2009 18:36:00 -0000
vti_syncwith_localhost\\\\\\research\\root\\web\\external\\users\\jinl\\pv2009///research/root/web/external/users/jinl/pv2009:TX|17 Jul 2008 00:02:50 -0000
vti_syncofs_localhost\\\\\\research\\root\\web\\external\\users\\jinl\\pv2009///research/root/web/external/users/jinl/pv2009:TW|17 Jul 2008 02:08:42 -0000
vti_cacheddtm:TX|02 Apr 2009 18:36:00 -0000
vti_filesize:IR|1950
