vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|15 Apr 2009 01:00:07 -0000
vti_extenderversion:SR|12.0.0.4518
vti_author:SR|REDMOND\\jinl
vti_modifiedby:SR|REDMOND\\jinl
vti_timecreated:TR|02 Jul 2008 09:43:36 -0000
vti_syncwith_localhost\\\\\\research\\root\\web\\external\\http\\workshops\\pv2009///research/root/web/external/http/workshops/pv2009:TX|17 Jul 2008 01:46:27 -0000
vti_syncofs_localhost\\\\\\research\\root\\web\\external\\http\\workshops\\pv2009///research/root/web/external/http/workshops/pv2009:TW|17 Jul 2008 01:59:22 -0000
vti_nexttolasttimemodified:TW|04 Apr 2009 00:28:45 -0000
vti_syncwith_localhost\\\\\\research\\root\\web\\external\\users\\jinl\\pv2009///research/root/web/external/users/jinl/pv2009:TX|17 Jul 2008 01:46:27 -0000
vti_backlinkinfo:VX|
vti_syncofs_localhost\\\\\\research\\root\\web\\external\\users\\jinl\\pv2009///research/root/web/external/users/jinl/pv2009:TW|17 Jul 2008 02:08:42 -0000
vti_cacheddtm:TX|15 Apr 2009 01:00:07 -0000
vti_filesize:IR|558
