vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|07 May 2009 20:53:39 -0000
vti_extenderversion:SR|12.0.0.4518
vti_author:SR|REDMOND\\jinl
vti_modifiedby:SR|REDMOND\\jinl
vti_timecreated:TR|12 Oct 2007 05:34:00 -0000
vti_backlinkinfo:VX|
vti_syncwith_localhost\\\\\\research\\root\\web\\external\\http\\workshops\\pv2009///research/root/web/external/http/workshops/pv2009:TX|17 Jul 2008 02:34:09 -0000
vti_syncofs_localhost\\\\\\research\\root\\web\\external\\http\\workshops\\pv2009///research/root/web/external/http/workshops/pv2009:TW|17 Jul 2008 02:34:43 -0000
vti_nexttolasttimemodified:TW|07 May 2009 20:53:37 -0000
vti_syncwith_localhost\\\\\\research\\root\\web\\external\\users\\jinl\\pv2009///research/root/web/external/users/jinl/pv2009:TX|17 Jul 2008 02:34:09 -0000
vti_syncofs_localhost\\\\\\research\\root\\web\\external\\users\\jinl\\pv2009///research/root/web/external/users/jinl/pv2009:TW|17 Jul 2008 02:34:28 -0000
vti_cacheddtm:TX|07 May 2009 20:53:37 -0000
vti_filesize:IR|445
