vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|25 Mar 2009 18:14:32 -0000
vti_extenderversion:SR|12.0.0.4518
vti_author:SR|REDMOND\\jinl
vti_modifiedby:SR|REDMOND\\jinl
vti_timecreated:TR|16 Jul 2008 20:41:49 -0000
vti_title:SR|PV 2009 <?php if(isset($page_title)) { if (!empty($page_title)) { echo (" - $page_title"); } } else { $filename = $_SERVER['SCRIPT_FILENAME']; $filename = preg_replace("/^.*\\//","",$filename); $filename = preg_replace("/.php$/","",$filename); echo(" - $filename"); } ?> 
vti_backlinkinfo:VX|
vti_nexttolasttimemodified:TW|17 Jul 2008 23:05:24 -0000
vti_syncwith_localhost\\\\\\research\\root\\web\\external\\http\\workshops\\pv2009///research/root/web/external/http/workshops/pv2009:TX|17 Jul 2008 21:43:17 -0000
vti_syncofs_localhost\\\\\\research\\root\\web\\external\\http\\workshops\\pv2009///research/root/web/external/http/workshops/pv2009:TW|17 Jul 2008 21:44:26 -0000
vti_syncwith_localhost\\\\\\research\\root\\web\\external\\users\\jinl\\pv2009///research/root/web/external/users/jinl/pv2009:TX|17 Jul 2008 21:48:33 -0000
vti_syncofs_localhost\\\\\\research\\root\\web\\external\\users\\jinl\\pv2009///research/root/web/external/users/jinl/pv2009:TW|17 Jul 2008 21:48:51 -0000
vti_cacheddtm:TX|17 Jul 2008 23:01:07 -0000
vti_filesize:IR|852
