vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|17 Jul 2008 01:57:55 -0000
vti_extenderversion:SR|12.0.0.4518
vti_author:SR|REDMOND\\jinl
vti_modifiedby:SR|REDMOND\\jinl
vti_timecreated:TR|03 Nov 2007 08:27:38 -0000
vti_backlinkinfo:VX|
vti_syncwith_localhost\\\\\\research\\root\\web\\external\\http\\workshops\\pv2009///research/root/web/external/http/workshops/pv2009:TX|17 Jul 2008 01:57:55 -0000
vti_syncofs_localhost\\\\\\research\\root\\web\\external\\http\\workshops\\pv2009///research/root/web/external/http/workshops/pv2009:TW|17 Jul 2008 01:59:23 -0000
vti_syncwith_localhost\\\\\\research\\root\\web\\external\\users\\jinl\\pv2009///research/root/web/external/users/jinl/pv2009:TX|17 Jul 2008 01:57:55 -0000
vti_nexttolasttimemodified:TW|17 Jul 2008 01:04:32 -0000
vti_cacheddtm:TX|17 Jul 2008 01:57:55 -0000
vti_filesize:IR|15925
vti_syncofs_localhost\\\\\\research\\root\\web\\external\\users\\jinl\\pv2009///research/root/web/external/users/jinl/pv2009:TW|17 Jul 2008 02:08:42 -0000
